export {
  TASK_TITLE_MAX_LENGTH,
  TASK_DESCRIPTION_MAX_LENGTH,
  TASK_SLUG_MAX_LENGTH,
  TASK_RECURRENCE_RULE_MAX_LENGTH,
  TASK_IMPORT_MAX_ROWS,
  TASK_FOLLOW_UP_DELAY_MAX_DAYS,
} from '@pomi/shared';
